--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 8.0.864
--   Created On : Monday, 08 October, 2012 
--   DBMS       : PostgreSQL 
--   -------------------------------------------------- 



--  Drop Tables, Stored Procedures and Views 

DROP TABLE IF EXISTS Arch CASCADE
;
DROP TABLE IF EXISTS BuildClients CASCADE
;
DROP TABLE IF EXISTS Distribution CASCADE
;
DROP TABLE IF EXISTS Format CASCADE
;
DROP TABLE IF EXISTS Job CASCADE
;
DROP TABLE IF EXISTS JobStatus CASCADE
;
DROP TABLE IF EXISTS Package CASCADE
;
DROP TABLE IF EXISTS PackageInstance CASCADE
;
DROP TABLE IF EXISTS Status CASCADE
;
DROP TABLE IF EXISTS Suite CASCADE
;

--  Create Tables 
CREATE TABLE Arch ( 
	id SERIAL PRIMARY KEY,
	Name text
)
;

CREATE TABLE BuildClients ( 
	id SERIAL PRIMARY KEY,
	Name text
)
;

CREATE TABLE Distribution ( 
	id SERIAL PRIMARY KEY,
	Name text
)
;
COMMENT ON TABLE Distribution
    IS 'For example this could be Debian Squeeze, Ubuntu, Windows 7'
;

CREATE TABLE Format ( 
	id SERIAL PRIMARY KEY,
	Name text
)
;
COMMENT ON TABLE Format
    IS 'This is the format of the package instance, for example MSI, deb, rpm, tarball'
;

CREATE TABLE Job ( 
	id SERIAL PRIMARY KEY,
	PackageInstance_id bigint,
	BuildClient_id bigint
)
;
COMMENT ON TABLE Job
    IS 'A Job is how we build a given package instance, multiple jobs may be submitted for a single package.'
;

CREATE TABLE JobStatus ( 
	id SERIAL PRIMARY KEY,
	Job_id bigint,
	Status_id bigint,
	time timestamp
)
;

CREATE TABLE Package ( 
	id SERIAL PRIMARY KEY,
	Version text,
	Name text
)
;

CREATE TABLE PackageInstance ( 
	id SERIAL PRIMARY KEY,
	Package_id bigint,
	Arch_id bigint,
	Suite_id bigint,
	Dist_id bigint,
	Format_id bigint,
	master boolean NOT NULL DEFAULT false   --  Master tell us if this instance is the first submitted for a given package, this information is acted on by certain build clients 
)
;
COMMENT ON COLUMN PackageInstance.master
    IS 'Master tell us if this instance is the first submitted for a given package, this information is acted on by certain build clients'
;

CREATE TABLE Status ( 
	id SERIAL PRIMARY KEY,
	Name text
)
;

CREATE TABLE Suite ( 
	id SERIAL PRIMARY KEY,
	Name text
)
;


--  Create Indexes 
ALTER TABLE Arch
	ADD CONSTRAINT UQ_Arch_id UNIQUE (id)
;
ALTER TABLE BuildClients
	ADD CONSTRAINT UQ_BuildClients_id UNIQUE (id)
;
ALTER TABLE Distribution
	ADD CONSTRAINT UQ_Distribution_id UNIQUE (id)
;
ALTER TABLE Format
	ADD CONSTRAINT UQ_Format_id UNIQUE (id)
;
ALTER TABLE Job
	ADD CONSTRAINT UQ_Job_id UNIQUE (id)
;
ALTER TABLE JobStatus
	ADD CONSTRAINT UQ_JobStatus_id UNIQUE (id)
;
ALTER TABLE Package
	ADD CONSTRAINT UQ_Package_id UNIQUE (id)
;
ALTER TABLE PackageInstance
	ADD CONSTRAINT UQ_PackageInstance_id UNIQUE (id)
;
ALTER TABLE Status
	ADD CONSTRAINT UQ_Status_id UNIQUE (id)
;
ALTER TABLE Suite
	ADD CONSTRAINT UQ_Suite_id UNIQUE (id)
;

--  Create Foreign Key Constraints 
ALTER TABLE Job ADD CONSTRAINT FK_Job_BuildClients 
	FOREIGN KEY (BuildClient_id) REFERENCES BuildClients (id)
;

ALTER TABLE Job ADD CONSTRAINT FK_Job_PackageInstance 
	FOREIGN KEY (PackageInstance_id) REFERENCES PackageInstance (id)
;

ALTER TABLE JobStatus ADD CONSTRAINT FK_JobStatus_Job 
	FOREIGN KEY (Job_id) REFERENCES Job (id)
;

ALTER TABLE JobStatus ADD CONSTRAINT FK_JobStatus_Status 
	FOREIGN KEY (Status_id) REFERENCES Status (id)
;

ALTER TABLE PackageInstance ADD CONSTRAINT FK_PackageInstance_Arch 
	FOREIGN KEY (Arch_id) REFERENCES Arch (id)
;

ALTER TABLE PackageInstance ADD CONSTRAINT FK_PackageInstance_Distribution 
	FOREIGN KEY (Dist_id) REFERENCES Distribution (id)
;

ALTER TABLE PackageInstance ADD CONSTRAINT FK_PackageInstance_Format 
	FOREIGN KEY (Format_id) REFERENCES Format (id)
;

ALTER TABLE PackageInstance ADD CONSTRAINT FK_PackageInstance_Package 
	FOREIGN KEY (Package_id) REFERENCES Package (id)
;

ALTER TABLE PackageInstance ADD CONSTRAINT FK_PackageInstance_Suite 
	FOREIGN KEY (Suite_id) REFERENCES Suite (id)
;
